version: '3.8'

services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5430:5432"
  http_server:
    build: ./py-conveyor-service/
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./py-conveyor-service/:/app
